backend:
  name: git-gateway
  branch: main  # or master

media_folder: "static/images"  # Adjust based on your Hugo structure
public_folder: "/images"

collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
